############
# MORPHEUS #
############

# should we set the players bed spawn when he rightclicks his bed?
set-bed-spawn: true

# should we inform players about night skipping through titles?
inform-with-title: true

# the percentage of players that have to sleep for the night to be skipped.
share-of-players: 0.5

# some messages you may modify however you want!
# placeholders:
# %player% - the name of the player
# %sleeping% - the percentage of players currently sleeping
# %version% - this plugins current version
messages:
  set-spawn: "&aBed spawn set"
  no-permission: "&4No permission"
  good-morning: "&6Good morning! The night was skipped"
  went-to-bed: "&f%player%&7 went to bed (%sleeping%% sleeping)"
  left-bed: "&f%player%&7 left the bed (%sleeping%% sleeping)"
  default: "&7You're running Morpheus %version%\n&7Commands:\n&7 — &f/morpheus toggle&7: toggle the plugin"
  enabled: "&aSleep voting is now activated"
  disabled: "&7Sleep voting is now inactivated"
  not-enough-args: "&4Not enough arguments"