set-bed-spawn: true
inform-with-title: true
share-of-players: 0.5
messages:
  set-spawn: "&aBed spawn set"
  no-permission: "&4No permission"
  good-morning: "&6Good morning! The night was skipped"
  went-to-bed: "&f%player%&7 went to bed (%sleeping%% sleeping)"
  left-bed: "&f%player%&7 left the bed (%sleeping%% sleeping)"
  default: "&7You're running Morpheus %version%\n&7Commands:\n&7 — &f/morpheus toggle&7: toggle the plugin"
  enabled: "&aSleep voting is now activated"
  disabled: "&7Sleep voting is now inactivated"
  not-enough-args: "&4Not enough arguments"