main: net.overcrave.morpheus.main.Morpheus
name: Morpheus
version: 0.6-SNAPSHOT
api-version: 1.13
description: 'Morpheus allows to skip the night if the specified percentage of players are asleep.'
author: OverCrave
authors: [Mdash, CMDR_Tvis]
commands:
  morpheus:
    description: '/morpheus toggle — toggle the plugin'
    permission: morpheus.toggle
permission:
  morpheus.toggle:
    default: op
  morpheus.*:
    default: op
    children:
      morpheus.control: true